### ISSUE TITLE
Duplicate sites can be created

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#101]
A better primary key needs to be defined for sites.  
options:
- Site_name + location (city_name+country)
- Site_name + date_time

**Comment by jlark** [comment]
Let's make the name field unique for Sesh_Site

**Comment by Frankkwizera** [comment]
yeah!

**Comment by mugijanvier** [comment]
hello Tilev !! whats up?? me i am ok!!

2016-06-02 16:02 GMT+02:00 Frank <notifications@github.com>:
