### ISSUE TITLE
JS library versions

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#121]
Make sure the JS library version is included in bower components. @rawjazz @Frankkwizera @upatricck 
This will make deployments easier as we'll know which version of the code is needed and will avoid dependency conflicts.

**Comment by jlark** [comment]
Just put he latest code in prod.
JS libraries that are not resolving are
    1) babel#* which resolved to d54d59ff74 and is required by components
    2) babel#d54d59ff74 which resolved to d54d59ff74
`
Prefix the choice with ! to persist it to bower.json

? Answer 1

Unable to find a suitable version for d3, please choose one:
    1) d3#~3.3.13 which resolved to 3.3.13 and is required by nvd3#1.7.1
    2) d3#3.5.x which resolved to 3.5.16 and is required by calendar-heatmap#0.3.0
    3) d3#3.5.16 which resolved to 3.5.16

Prefix the choice with ! to persist it to bower.json

? Answer 3

Unable to find a suitable version for react, please choose one:
    1) react#0.14.8 which resolved to 0.14.8
    2) react#^15.0.1 which resolved to 15.0.1 and is required by components

Prefix the choice with ! to persist it to bower.json
`

**Comment by jlark** [comment]
correct link here. sesh-prod1.westeurope.cloudapp.azure.com

**Comment by upatricck** [comment]
The version are now specified
