### ISSUE TITLE
maindash board react error

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#124]
getting 
`sesh_react.js:97 Uncaught TypeError: this.props.data.map is not a function`
on main dashboard.

**Comment by upatricck** [comment]
Also working here, when the conditions to fail?

**Comment by jlark** [comment]
it's happening after a fresh deploy. 
Perhaps wrong version of react?
You can see it here.
http://prod1.westeurope.cloudapp.azure.com

**Comment by jlark** [comment]
Looks like this was fixed in #122 or #121
