### ISSUE TITLE
Historical charts aren't working

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#126]
Pages is stuck in loading mode.

with error
`Uncaught TypeError: calendarHeatmap(...).data(...).tooltipUnit is not a function` in historical.js

**Comment by upatricck** [comment]
It seems that they are working on my side, any special conditions to make it fail.?

**Comment by upatricck** [comment]
If it is about tooltipUnit function it is the one we modified in calendarHeatmap not sure if the library used on bower is using it.

**Comment by jlark** [comment]
Does this depend on the owner of the repository of calendarHeatmap  creating a new release?
If that is the case it might be good to include our version of the JS library in sesh-ui until the author creates a new release.

**Comment by upatricck** [comment]
We changed to using our version of the library.

**Comment by jlark** [comment]
#129 sorted out
