### ISSUE TITLE
Graphs issues

### ISSUE THREAD

**Issue by rawjazz** [GreatLakesEnergy/sesh-dash-beta#159]
Graphs were enhanced using test_db
Measurements founded in that database was assigned to an SI untits
dictionary in models 
So as Sesh_db have more measurements than those in the test_db,
Some Measurements lacks the SI units and this causes an error

**Comment by jlark** [comment]
The best way to handle this is by adding the Units to a new model.

I think these belong in each model separately but not in a unified Dictionary.

**Comment by Frankkwizera** [comment]
decided to put all in Daily data point model

**Comment by jlark** [comment]
They shouldn't all be in one model.
They should be either in their own class? Meaning there is a class that manages all of them.
or in their respective classes. Does this make sense?
