### ISSUE TITLE
Status Card always showing one hour behind

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#175]
![image](https://cloud.githubusercontent.com/assets/956722/15315128/176fea6a-1c16-11e6-9a2b-a0ab84334f4f.png)

**Comment by jlark** [comment]
I think this has to do with the dates on the data points coming in
![image](https://cloud.githubusercontent.com/assets/956722/15448415/8d099c3c-1f61-11e6-92a3-613548f89d94.png)

is when I hve 2:37PM on my local time.

**Comment by upatricck** [comment]
I switched the time not to use the rmc_status data_point but to use the time for the points in influx.
If  it is  a problem with the latest data_point think it should be fixed

**Comment by jlark** [comment]
Let me investigate.  I suspect this is tied to the timezone.

**Comment by jlark** [comment]
Looks like time on the server is set to UTC

dev@sesh-prod1:~/sesh-dash/src/sesh$ date
Sat May 21 17:08:36 UTC 2016

when actual local time is 19:12

**Comment by jlark** [comment]
http://sesh-dev.westeurope.cloudapp.azure.com:8080/dash/2

Looks like this is ok now.
