### ISSUE TITLE
Move Alert tirggers to user

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#184]
Move attribute to send sms, email to user rather than the rule object.

This is difficult to manage and should simply be a user setting.

**Comment by upatricck** [comment]
What should we do with the on_call user?

**Comment by jlark** [comment]
If user is on call it should have all of the alert mechanisms enabled by default.

Mobile typing




On Thu, May 19, 2016 at 5:35 AM -0700, "Uwonkunda Patrick" <notifications@github.com> wrote:












What should we do with the on_call user?

**Comment by jlark** [comment]
Was this done? I don't see reference in PR!

**Comment by upatricck** [comment]
No its not yet done, but it will be done soon.
