### ISSUE TITLE
log formatting broken

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#192]
DEBUG 2016-05-21 14:25:56,014 influx
DEBUG 2016-05-21 14:25:56,138 influx
DEBUG 2016-05-21 14:25:56,155 influx
DEBUG 2016-05-21 14:26:12,808 influx
DEBUG 2016-05-21 14:26:12,872 influx
DEBUG 2016-05-21 14:26:12,910 influx
DEBUG 2016-05-21 14:27:35,068 tasks
DEBUG 2016-05-21 14:27:35,089 tasks
DEBUG 2016-05-21 14:27:35,124 tasks
DEBUG 2016-05-21 14:27:35,130 tasks
DEBUG 2016-05-21 14:27:35,186 tasks
WARNING 2016-05-21 14:27:35,186 tasks
DEBUG 2016-05-21 14:28:47,176 influx
DEBUG 2016-05-21 14:28:47,369 influx
DEBUG 2016-05-21 14:28:47,400 influx
INFO 2016-05-21 14:29:02,827 victron
DEBUG 2016-05-21 14:29:03,483 influx
DEBUG 2016-05-21 14:29:03,483 influx
DEBUG 2016-05-21 14:29:03,483 influx
DEBUG 2016-05-21 14:29:03,484 influx
DEBUG 2016-05-21 14:29:03,484 influx

**Comment by jlark** [comment]
'verbose': {                                                      
            'format': '%(levelname)s %(asctime)s %(module)s %(message)',  
        },                                                                
        'simple': {                                                       
            'format': '%(levelname)s %(message)s'                         
        },

**Comment by jlark** [comment]
modified accordingly

**Comment by upatricck** [comment]
How should the format be?

**Comment by jlark** [comment]
The message is missing. I've changed this. will send PR
