### ISSUE TITLE
Upgrade to new dashboard template

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#212]
Use themeforest template.
Let's start with the login screen.

Please follow the existing template style.

**Comment by jlark** [comment]
Will split this up into multiple tasks

**Comment by rawjazz** [comment]
i think if everyone would review his code in the sesh_dashboard.js file and put proper comments on each function 
would be a good start

**Comment by upatricck** [comment]
Yeah that's a good idea, most of our code is not clear and we should fix indentation.

**Comment by Frankkwizera** [comment]
Going to start by with nav bar.

**Comment by jlark** [comment]
lot's of errors on historical page or all pages?

![image](https://cloud.githubusercontent.com/assets/956722/16480854/b84bd6a6-3ea8-11e6-8fd9-705d2e538fa3.png)


also footer should be pushed down.

![image](https://cloud.githubusercontent.com/assets/956722/16480885/d5f4113c-3ea8-11e6-859c-357352933bbe.png)


and data is not loading.
