### ISSUE TITLE
alert email template doesn't show alert data

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#213]
![image](https://cloud.githubusercontent.com/assets/956722/15605459/58fc30b8-2406-11e6-9892-89f12e7337b3.png)

**Comment by upatricck** [comment]
![screenshot from 2016-05-28 22 45 08](https://cloud.githubusercontent.com/assets/8204177/15629877/e7046716-2525-11e6-9bd3-8615f35edfe1.png)

Fixed now showing the alert message

Any other enhancements on the message?
