### ISSUE TITLE
Historical page not rendering alerts and site settings

### ISSUE THREAD

**Issue by Frankkwizera** [GreatLakesEnergy/sesh-dash-beta#226]

**Comment by upatricck** [comment]
Yeah, This is a problem about the way the historical js was added, we created a block of sesh js so the js files for the historical page overwrites the seesh js. 

I think we can fix this in the new dashoard??

**Comment by jlark** [comment]
Is it a hard fix? Is this not loading due to permissions?

**Comment by rawjazz** [comment]
no it's not due to permissions

**Comment by upatricck** [comment]
No its not about permissions, It is that the code that pulls the alert for messages is not in the historical js.

**Comment by jlark** [comment]
Ok, in that case it should be fixed. I want to have a stable build before we upgrade the UI.

**Comment by upatricck** [comment]
We removed it because it was selecting elements that were not on the historical page and which was causing errors,

Finding a way to call the alerts in the historical js would help.

**Comment by jlark** [comment]
Why are alerts needed in the historical.js?

**Comment by upatricck** [comment]
They are needed for the notifications on the navigation bar.

**Comment by jlark** [comment]
ok, makes sense then shouldn't they be in the main base template? so they are included on every page?

**Comment by rawjazz** [comment]
the historical data page doesn't inherit the sesh_dash.js file
so this may be what is causing the bug

**Comment by jlark** [comment]
I remember there was a reason for this and we were looking at react routing for this purpose.

what is the recommended solution?
