### ISSUE TITLE
status card appearing when import site forms

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#236]
![image](https://cloud.githubusercontent.com/assets/956722/15777699/afa4f4aa-2991-11e6-85e0-6048c48e9e90.png)

This should be hidden from the form

**Comment by Frankkwizera** [comment]
do u mean excluding it from the form or just hiding it from the user??!!!

**Comment by jlark** [comment]
check out `forms.py` simply add it to the exclude list and see if that works.
