### ISSUE TITLE
Make aggregation functions work with RMC data

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#261]
Currently data received from RMC is stored in influx with names that are not essentially identical with the ones in BOM data point.

This causes 2 issues. 

Firstly, status card cannot see the data coming in from the RMC.

Secondly, aggregation functions `aggregate_daily_data_point` which goes and calculates daily production and consumptino figures is also hard coded to work with BOM_data_point fields. this should also configurable so we can have it aggregate fields coming in from influx.

@upatricck I suggest you tackle the second piece as this ties in closely with the work you're doing now with data calculations.

@Frankkwizera @rawjazz I suggest you tackle the first piece as it ties into simlarly to the graphing piece.

**Comment by jlark** [comment]
any thoughts on this? questions , concerns?

**Comment by upatricck** [comment]
What are the names of the rmc data?

**Comment by rawjazz** [comment]
making the names of the rmc data identical to the ones of Bom would solve the issue or there is another path we have to understand?

**Comment by jlark** [comment]
That would indeed be a quick fix

**Comment by jlark** [comment]
Youn can see them by querying influx for aite name nyange

**Comment by Frankkwizera** [comment]
so we have to change them from sesh APi

**Comment by jlark** [comment]
I can try to do this.

**Comment by upatricck** [comment]
How should we continue on this, since now we need to present data from clients on the dashboard and the RMC Data is not shown on the dashboard.

**Comment by jlark** [comment]
I think we need a new panel a new tab on the dashboard like the way @Frankkwizera  did with the settings page that can show aggregate data. 

I'd like you @upatricck to speak to Ivan and Sam about which data is necessary should be shown and how it should be represented. The status card is working but I think we also need a way to show the aggregate data (Like kWh generated, grid used basically the aggregate  counters.)
