### ISSUE TITLE
status card link is broken to sesh_site

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#262]
![image](https://cloud.githubusercontent.com/assets/956722/15888657/06e22be6-2d68-11e6-9318-0c5c7fcea51b.png)

error can be repeated here.
http://sesh-dev.westeurope.cloudapp.azure.com:8080/admin/seshdash/sesh_site/4/change/

is this tied to the problem with the OneToOne  field?

https://github.com/GreatLakesEnergy/sesh-dash-beta/blob/master/seshdash/models.py#L121

I think this might be due to having an orphan status card in the status_card table. 
![image](https://cloud.githubusercontent.com/assets/956722/15888773/98291646-2d68-11e6-9941-4fc76044434d.png)

**Comment by upatricck** [comment]
Yeah that should be the problem

**Comment by upatricck** [comment]
How can it be fixed,

Deleting the orphan status card ?

**Comment by jlark** [comment]
yes, i'm trying to do this now.

**Comment by rawjazz** [comment]
did you delete a site?

**Comment by jlark** [comment]
Deleting the orphan row from mysql solved this issue. 
I'm curious how we ended up with an orphan row though.

**Comment by upatricck** [comment]
Maybe we should override the delete of the sesh_site so that whenever a site is deleted its status card should be deleted.

**Comment by jlark** [comment]
@upatricck I think that's a good idea the delete cascade was helpfull in this way.
