### ISSUE TITLE
daily aggregate values have battery voltage

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#273]
![image](https://cloud.githubusercontent.com/assets/956722/16539986/80106eca-4054-11e6-8077-71818687e773.png)

battery voltage shouldn't be in daily aggregates? Any idea how this got here?

**Comment by upatricck** [comment]
No idea, But will check it out.

**Comment by jlark** [comment]
414   daily_pv_yield = models.FloatField(default=0,
415	            verbose_name="Battery Voltage") # Aggregate pv produced that day Kwh
416	    daily_power_consumption_total = models.FloatField(default=0,

looks like a simple fix

**Comment by upatricck** [comment]
So it is the verbose name??

**Comment by jlark** [comment]
yes correcting that shuold be fine I'll take care of this

**Comment by upatricck** [comment]
Okay.
