### ISSUE TITLE
limit what's shown in graph in main dashboard

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#276]
![image](https://cloud.githubusercontent.com/assets/956722/16579243/18b13f6e-429f-11e6-948e-8bfb989a7e91.png)

I think this drop down should not show all measurements but only those we specify. 
It should also display the verbose names and not the verbatim as it's very confusing.

pv_production - PV Yield
soc - Battery State of Charge
AC_load -  Power used from grid
Battery_voltage -  Battery Voltage
cloud_cover - Cloud Cover

I ideally you can keep this information in the model. And should be easy to edit and expand.

**Comment by rawjazz** [comment]
What should the limit be based on?
