### ISSUE TITLE
Deleting site is not automatically deleting sesh site

### ISSUE THREAD

**Issue by upatricck** [GreatLakesEnergy/sesh-dash-beta#285]
When deleting a sesh Site its associated status card should also be deleted in order to prevent RelatedObjectsDoesNotExist exception due to orpan status card.

**Comment by jlark** [comment]
I though  we had changed this for a reason!
If a site is deleted it's status card should also be deleted.

**Comment by upatricck** [comment]
Fixed in pull request #
