### ISSUE TITLE
show loading indicator when update graph is selected

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#289]
![image](https://cloud.githubusercontent.com/assets/956722/16691673/d5d8ee58-452d-11e6-885e-7c0e91586b01.png)

currently when update graph is clicked there is no indicator that indicates anything is happening. 
Please apply the top load bar to this.

**Comment by Frankkwizera** [comment]
what about the spinner like the one on historical page

**Comment by jlark** [comment]
Can we use the loader bar on top?

Mobile typing




On Fri, Jul 8, 2016 at 5:48 PM +0200, "Frank" <notifications@github.com> wrote:












what about the spinner like the one on historical page
