### ISSUE TITLE
Highcharts not defined in bower componentes

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#31]
Hi Janvier,
I don't see highcharts defined in bower_components. As a result it's note downloaded when I run
python manage.py bower_install.

BOWER_INSTALLED_APPS = (
            'jquery#1.9',
            'mapbox.js',
            'd3#3.3.13',
            'nvd3#1.7.1',
            )

Please can you fix this.

**Comment by mugijanvier** [comment]
yes the problem is that after putting it the borrow ask me the Update which
cause the 301 file in the pull request!! can i do its???

2015-12-18 10:07 GMT+02:00 Alp Tilev <notifications@github.com>:

**Comment by jlark** [comment]
I've already fixes this.I'm moved all the javascript components to Bower.

Please look at the other issue.

**Comment by mugijanvier** [comment]
yes, it ok!
