### ISSUE TITLE
Potential issue during installation

### ISSUE THREAD

**Issue by sbagri** [GreatLakesEnergy/sesh-dash-beta#323]
I am following step 1 of https://github.com/GreatLakesEnergy/sesh-dash-beta#before-you-start
In that it asks to provide a default value and suggests we can pass timezone.now() but later while running "python manage.py migrate" it fails as it expects an integer value

some relevant part of lines on terminal

------------------
vagrant@vagrant-ubuntu-trusty-64:~/dev/sesh$ python manage.py makemigrations
You are trying to change the nullable field 'emonpi' on sesh_site to non-nullable without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows)
 2) Ignore for now, and let me handle existing rows with NULL myself (e.g. because you added a RunPython or RunSQL operation to handle NULL values in a previous data migration)
 3) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now()
-------------
if we give timezone.now(), the migrate file is created properly but while applying that migration it fails as there is some function which tries to covert the datetime to int such as
int(some variable)

**Comment by sbagri** [comment]
Ok, I passed a default value of 1 and made it work for now :)
but it would be great if the documentation is updated :)

**Comment by jlark** [comment]
@sbagri I've put this on the list todo. 

Thank
