### ISSUE TITLE
Add option to turn email reports on or off per site

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#334]
There should be an option each user to enable email reports per site.

This will be a user specific option.

So say user David who has permission to view and edit site Heaven. Would like to get email reports for this site. Were user Alp who also has the persmission to view the site but would like to turn email reports off.

**Comment by upatricck** [comment]
So should we create user settings models, or we could include this in the Sesh_User model as a boolean field?

**Comment by jlark** [comment]
I think we should start investigating a user settings model helper.
