### ISSUE TITLE
highcharts not working with weather data

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#34]
See below error I'm recieving 

 get_high_chart( date  , [0, 0.0, 0.0, 85464.74065971375, 0.0, 0.0, 123482.5954837799, 0.0, 0.0, 35662.47393989563, 0.0, 0.0, 62857.12724113464, 0.0, 0.0, 100732.5266418457, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  , [0.67, 0.59, 0.46, 0.61, 0.41, 0.31, 0.32, 0.52, 0.27, 0.23, 0.5, 0.48, 0.15, 0.41, 0.67, 0.18, 0.47, 0.23, 0.25, 0.92, &#39;...(remaining elements truncated)...&#39;])
});

Looks like there is problem in how you're calling the template data is getting truncated.

**Comment by mugijanvier** [comment]
In Mine there is no problem, how can i fix it??

**Comment by jlark** [comment]
Issue is closed Janvier. (it's fixed)

**Comment by mugijanvier** [comment]
u fixed its???

**Comment by jlark** [comment]
you did? This was the last PR you sent.

On Wed, Jan 6, 2016 at 2:22 PM, Mugisha janvier <notifications@github.com>
wrote:

> u fixed its???
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GreatLakesEnergy/sesh-dash-beta/issues/34#issuecomment-169311563>
> .
>



-- 
Alp
www.atilev.com

**Comment by mugijanvier** [comment]
ok
