### ISSUE TITLE
site name formatting breaks when in settings

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#346]
![image](https://cloud.githubusercontent.com/assets/956722/18715268/f9f34b82-8018-11e6-956a-a1b3cb708413.png)
 vs

![image](https://cloud.githubusercontent.com/assets/956722/18715287/08ba328e-8019-11e6-8103-090cdf2aa406.png)

**Comment by upatricck** [comment]
Fixed ..
