### ISSUE TITLE
Add data download section under data analysis submenu

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#369]
This page should have a drop down that allows the user to select X sites and for each site allow to select mutiple fields and provide a date range. 

This will eecute the query in influx format is as a CSV and let the user downoad it.
The priority on this feature is higher.

**Comment by upatricck** [comment]
This should be the next?

**Comment by jlark** [comment]
yes let's go with this.

**Comment by upatricck** [comment]
fixed #379
