### ISSUE TITLE
Change graph symbal to Wh

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#58]
Hi,
The Y axis values have the incorrect lable. It should be Wh for Watt hour nor HW.

**Comment by mugijanvier** [comment]
hey!! i was some how busy!! yes. to edit its u can find its in the
dashboard.js. it is only two lines to edit!!

2016-01-26 11:53 GMT+02:00 Alp Tilev <notifications@github.com>:

**Comment by jlark** [comment]
Fixed
