### ISSUE TITLE
Include MYSQL setup in ansible vagrant

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#6]
It would be great to include MYSQL installation with the vagrant image.

**Comment by dhruvkar** [comment]
Sure. So instead of using SQLite for development, we use MYSQL?

**Comment by alptilev** [comment]
I think so yes.

Alp

Sent from my Windows Phone
________________________________

**Comment by jlark** [comment]
I believe Cagil took care of this. No need Dhruv. closing
