### ISSUE TITLE
redis missing from playbook

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-dash-beta#9]
Looks like Redis is missing from the ansible playbook.

Redis is needed for celery to run as the message broker.

**Comment by dhruvkar** [comment]
Will add.

**Comment by dhruvkar** [comment]
Added redis-server and redis-tools to playbook.

**Comment by alptilev** [comment]
Thanks Dhruv will merge when back in from of pc

Sent from my Windows Phone
________________________________
